import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
import { Suspense } from "react";
import Loading from "@/components/Loading";

export const metadata: Metadata = {
  title: "Dashboard Final Inspection", 
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex">
      <Sidebar />
      <Suspense fallback={<Loading/>}>
        <main className="w-full">{children}</main>
      </Suspense>
    </div>
  );
}